<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260314240000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create cobranca tables for boletos, PIX and borderos with permissions.'; }
    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE borderos_pagamento (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, referencia VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'rascunho', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_BPG_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_BPG_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_BPG_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_BPG_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE borderos_pagamento_itens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, bordero_pagamento_id BIGINT UNSIGNED NOT NULL, titulo_parcela_id BIGINT UNSIGNED NOT NULL, valor DECIMAL(18,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', CONSTRAINT FK_BPGI_BORDERO FOREIGN KEY (bordero_pagamento_id) REFERENCES borderos_pagamento (id) ON DELETE CASCADE, CONSTRAINT FK_BPGI_PARCELA FOREIGN KEY (titulo_parcela_id) REFERENCES titulos_parcelas (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE borderos_recebimento (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, referencia VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'rascunho', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_BRC_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_BRC_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_BRC_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_BRC_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE borderos_recebimento_itens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, bordero_recebimento_id BIGINT UNSIGNED NOT NULL, titulo_parcela_id BIGINT UNSIGNED NOT NULL, valor DECIMAL(18,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', CONSTRAINT FK_BRCI_BORDERO FOREIGN KEY (bordero_recebimento_id) REFERENCES borderos_recebimento (id) ON DELETE CASCADE, CONSTRAINT FK_BRCI_PARCELA FOREIGN KEY (titulo_parcela_id) REFERENCES titulos_parcelas (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE boletos_remessa (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, codigo_remessa VARCHAR(100) NOT NULL, banco VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'gerada', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE KEY uk_boletos_remessa_codigo (company_id, codigo_remessa), KEY idx_boletos_remessa_lookup (company_id, empresa_id, unidade_id, status), CONSTRAINT FK_BREM_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_BREM_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_BREM_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_BREM_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE boletos_remessa_itens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, boleto_remessa_id BIGINT UNSIGNED NOT NULL, titulo_parcela_id BIGINT UNSIGNED NOT NULL, nosso_numero VARCHAR(100) NOT NULL, valor DECIMAL(18,2) NOT NULL, vencimento DATE NOT NULL COMMENT '(DC2Type:date_immutable)', status VARCHAR(30) NOT NULL DEFAULT 'pendente_registro', ocorrencia_retorno VARCHAR(50) DEFAULT NULL, data_ocorrencia DATE DEFAULT NULL COMMENT '(DC2Type:date_immutable)', UNIQUE KEY uk_boletos_remessa_itens_nosso_numero (nosso_numero), CONSTRAINT FK_BRI_REMESSA FOREIGN KEY (boleto_remessa_id) REFERENCES boletos_remessa (id) ON DELETE CASCADE, CONSTRAINT FK_BRI_PARCELA FOREIGN KEY (titulo_parcela_id) REFERENCES titulos_parcelas (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE boletos_retorno_itens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, boleto_remessa_item_id BIGINT UNSIGNED DEFAULT NULL, nosso_numero VARCHAR(100) NOT NULL, codigo_ocorrencia VARCHAR(50) NOT NULL, descricao VARCHAR(255) DEFAULT NULL, valor_recebido DECIMAL(18,2) NOT NULL, data_ocorrencia DATE NOT NULL COMMENT '(DC2Type:date_immutable)', linha_original LONGTEXT DEFAULT NULL, importado_em DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', KEY idx_boletos_retorno_lookup (company_id, empresa_id, unidade_id, nosso_numero), CONSTRAINT FK_BRET_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_BRET_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_BRET_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_BRET_ITEM FOREIGN KEY (boleto_remessa_item_id) REFERENCES boletos_remessa_itens (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pix_cobrancas (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, titulo_parcela_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, txid VARCHAR(100) NOT NULL, chave_pix VARCHAR(255) NOT NULL, valor DECIMAL(18,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', expiracao_segundos INT NOT NULL, calendario_gerado_em DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', calendario_expira_em DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', qr_code LONGTEXT DEFAULT NULL, copia_cola LONGTEXT DEFAULT NULL, UNIQUE KEY uk_pix_cobrancas_txid (txid), KEY idx_pix_cobrancas_lookup (company_id, empresa_id, unidade_id, status), CONSTRAINT FK_PIXC_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_PIXC_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_PIXC_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_PIXC_PARCELA FOREIGN KEY (titulo_parcela_id) REFERENCES titulos_parcelas (id) ON DELETE CASCADE, CONSTRAINT FK_PIXC_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pix_recebimentos (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, pix_cobranca_id BIGINT UNSIGNED NOT NULL, end_to_end_id VARCHAR(120) NOT NULL, txid VARCHAR(100) NOT NULL, valor DECIMAL(18,2) NOT NULL, payload_json JSON NOT NULL, recebido_em DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE KEY uk_pix_recebimentos_e2e (end_to_end_id), CONSTRAINT FK_PIXR_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_PIXR_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_PIXR_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_PIXR_COBRANCA FOREIGN KEY (pix_cobranca_id) REFERENCES pix_cobrancas (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE pix_eventos_webhook (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED DEFAULT NULL, unidade_id BIGINT UNSIGNED DEFAULT NULL, tipo_evento VARCHAR(100) NOT NULL, identificador_externo VARCHAR(120) DEFAULT NULL, payload_json JSON NOT NULL, recebido_em DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', KEY idx_pix_eventos_webhook_lookup (company_id, tipo_evento, identificador_externo), CONSTRAINT FK_PIXW_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_PIXW_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE SET NULL, CONSTRAINT FK_PIXW_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("INSERT INTO modulos (codigo, nome, status) SELECT 'cobranca', 'Cobrança', 'active' WHERE NOT EXISTS (SELECT 1 FROM modulos WHERE codigo='cobranca')");
        foreach ([['cobranca.boletos.remessas.create','Gerar remessas de boletos'],['cobranca.boletos.retornos.import','Importar retornos bancários'],['cobranca.pix.cobrancas.create','Criar cobranças PIX'],['cobranca.pix.webhooks.create','Registrar webhooks PIX'],['cobranca.pix.cobrancas.view','Listar cobranças PIX']] as [$codigo,$nome]) { $this->addSql("INSERT INTO permissoes (modulo_id, codigo, nome, status) SELECT id, '$codigo', '$nome', 'active' FROM modulos WHERE codigo='cobranca' AND NOT EXISTS (SELECT 1 FROM permissoes WHERE codigo='$codigo')"); }
        $this->addSql("INSERT INTO perfil_acesso_permissoes (perfil_acesso_id, permissao_id) SELECT p.id, perm.id FROM perfis_acesso p JOIN permissoes perm ON perm.codigo LIKE 'cobranca.%' WHERE p.codigo='company_admin' AND NOT EXISTS (SELECT 1 FROM perfil_acesso_permissoes x WHERE x.perfil_acesso_id=p.id AND x.permissao_id=perm.id)");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS pix_eventos_webhook');
        $this->addSql('DROP TABLE IF EXISTS pix_recebimentos');
        $this->addSql('DROP TABLE IF EXISTS pix_cobrancas');
        $this->addSql('DROP TABLE IF EXISTS boletos_retorno_itens');
        $this->addSql('DROP TABLE IF EXISTS boletos_remessa_itens');
        $this->addSql('DROP TABLE IF EXISTS boletos_remessa');
        $this->addSql('DROP TABLE IF EXISTS borderos_recebimento_itens');
        $this->addSql('DROP TABLE IF EXISTS borderos_recebimento');
        $this->addSql('DROP TABLE IF EXISTS borderos_pagamento_itens');
        $this->addSql('DROP TABLE IF EXISTS borderos_pagamento');
    }
}
