<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260314260000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create contabil and BI tables with seed data and permissions.'; }
    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE contas_contabeis (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, parent_id BIGINT UNSIGNED DEFAULT NULL, codigo VARCHAR(50) NOT NULL, nome VARCHAR(255) NOT NULL, tipo VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', UNIQUE KEY uk_contas_contabeis_company_codigo (company_id, codigo), KEY idx_contas_contabeis_lookup (company_id, tipo, status), CONSTRAINT FK_CONTA_CONTABIL_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_CONTA_CONTABIL_PARENT FOREIGN KEY (parent_id) REFERENCES contas_contabeis (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE lancamentos_contabeis (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, titulo_id BIGINT UNSIGNED DEFAULT NULL, data_lancamento DATE NOT NULL COMMENT '(DC2Type:date_immutable)', historico LONGTEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'posted', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', KEY idx_lancamentos_contabeis_lookup (company_id, empresa_id, unidade_id, data_lancamento, status), CONSTRAINT FK_LANC_CONTABIL_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_LANC_CONTABIL_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_LANC_CONTABIL_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_LANC_CONTABIL_TITULO FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE lancamentos_contabeis_itens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, lancamento_contabil_id BIGINT UNSIGNED NOT NULL, conta_contabil_id BIGINT UNSIGNED NOT NULL, natureza VARCHAR(10) NOT NULL, valor DECIMAL(18,2) NOT NULL, CONSTRAINT FK_LANC_CONTABIL_ITEM_LANC FOREIGN KEY (lancamento_contabil_id) REFERENCES lancamentos_contabeis (id) ON DELETE CASCADE, CONSTRAINT FK_LANC_CONTABIL_ITEM_CONTA FOREIGN KEY (conta_contabil_id) REFERENCES contas_contabeis (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE dre_grupos (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, codigo VARCHAR(50) NOT NULL, nome VARCHAR(255) NOT NULL, ordem INT NOT NULL, tipo_demonstracao VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', KEY idx_dre_grupos_lookup (company_id, ordem, status), CONSTRAINT FK_DRE_GRUPO_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE dre_mapeamento_categorias (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, dre_grupo_id BIGINT UNSIGNED NOT NULL, categoria_financeira_id BIGINT UNSIGNED NOT NULL, CONSTRAINT FK_DRE_MAP_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_DRE_MAP_GRUPO FOREIGN KEY (dre_grupo_id) REFERENCES dre_grupos (id) ON DELETE CASCADE, CONSTRAINT FK_DRE_MAP_CATEGORIA FOREIGN KEY (categoria_financeira_id) REFERENCES categorias_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE contas_financeiras_saldos_diarios (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, data_saldo DATE NOT NULL COMMENT '(DC2Type:date_immutable)', saldo DECIMAL(18,2) NOT NULL, UNIQUE KEY uk_cfsd_contexto_data (company_id, empresa_id, unidade_id, conta_financeira_id, data_saldo), CONSTRAINT FK_SALDO_DIARIO_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_SALDO_DIARIO_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_SALDO_DIARIO_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_SALDO_DIARIO_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE indicadores_financeiros (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, codigo VARCHAR(100) NOT NULL, nome VARCHAR(255) NOT NULL, data_referencia DATE NOT NULL COMMENT '(DC2Type:date_immutable)', valor DECIMAL(18,4) NOT NULL, metadata_json JSON NOT NULL, KEY idx_indicadores_financeiros_lookup (company_id, empresa_id, unidade_id, codigo, data_referencia), CONSTRAINT FK_IND_FIN_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_IND_FIN_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_IND_FIN_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE snapshots_fluxo_caixa (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, data_referencia DATE NOT NULL COMMENT '(DC2Type:date_immutable)', saldo_inicial DECIMAL(18,2) NOT NULL, entradas_periodo DECIMAL(18,2) NOT NULL, saidas_periodo DECIMAL(18,2) NOT NULL, saldo_final DECIMAL(18,2) NOT NULL, UNIQUE KEY uk_snapshots_fluxo_caixa_contexto_data (company_id, empresa_id, unidade_id, data_referencia), CONSTRAINT FK_SNAPSHOT_CAIXA_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_SNAPSHOT_CAIXA_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_SNAPSHOT_CAIXA_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("INSERT INTO modulos (codigo, nome, status) SELECT 'contabil', 'Contábil e BI', 'active' WHERE NOT EXISTS (SELECT 1 FROM modulos WHERE codigo='contabil')");
        foreach ([['contabil.contas_contabeis.view','Listar contas contábeis'],['contabil.contas_contabeis.create','Criar contas contábeis'],['contabil.lancamentos_contabeis.create','Criar lançamentos contábeis'],['contabil.dre.view','Visualizar DRE'],['contabil.indicadores.view','Visualizar indicadores financeiros']] as [$codigo,$nome]) { $this->addSql("INSERT INTO permissoes (modulo_id, codigo, nome, status) SELECT id, '$codigo', '$nome', 'active' FROM modulos WHERE codigo='contabil' AND NOT EXISTS (SELECT 1 FROM permissoes WHERE codigo='$codigo')"); }
        $this->addSql("INSERT INTO perfil_acesso_permissoes (perfil_acesso_id, permissao_id) SELECT p.id, perm.id FROM perfis_acesso p JOIN permissoes perm ON perm.codigo LIKE 'contabil.%' WHERE p.codigo='company_admin' AND NOT EXISTS (SELECT 1 FROM perfil_acesso_permissoes x WHERE x.perfil_acesso_id=p.id AND x.permissao_id=perm.id)");
        $this->addSql("INSERT INTO dre_grupos (company_id, codigo, nome, ordem, tipo_demonstracao, status) SELECT c.id, 'receitas', 'Receitas', 10, 'resultado', 'active' FROM companies c WHERE NOT EXISTS (SELECT 1 FROM dre_grupos dg WHERE dg.company_id = c.id AND dg.codigo = 'receitas')");
        $this->addSql("INSERT INTO dre_grupos (company_id, codigo, nome, ordem, tipo_demonstracao, status) SELECT c.id, 'despesas', 'Despesas', 20, 'resultado', 'active' FROM companies c WHERE NOT EXISTS (SELECT 1 FROM dre_grupos dg WHERE dg.company_id = c.id AND dg.codigo = 'despesas')");
        $this->addSql("INSERT INTO dre_grupos (company_id, codigo, nome, ordem, tipo_demonstracao, status) SELECT c.id, 'resultado', 'Resultado', 30, 'resultado', 'active' FROM companies c WHERE NOT EXISTS (SELECT 1 FROM dre_grupos dg WHERE dg.company_id = c.id AND dg.codigo = 'resultado')");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS snapshots_fluxo_caixa');
        $this->addSql('DROP TABLE IF EXISTS indicadores_financeiros');
        $this->addSql('DROP TABLE IF EXISTS contas_financeiras_saldos_diarios');
        $this->addSql('DROP TABLE IF EXISTS dre_mapeamento_categorias');
        $this->addSql('DROP TABLE IF EXISTS dre_grupos');
        $this->addSql('DROP TABLE IF EXISTS lancamentos_contabeis_itens');
        $this->addSql('DROP TABLE IF EXISTS lancamentos_contabeis');
        $this->addSql('DROP TABLE IF EXISTS contas_contabeis');
    }
}
