<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260314233000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create tesouraria and conciliacao tables with permissions.'; }
    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE extratos_bancarios (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, codigo_externo VARCHAR(100) DEFAULT NULL, data_movimento DATE NOT NULL COMMENT '(DC2Type:date_immutable)', valor DECIMAL(18,2) NOT NULL, tipo VARCHAR(20) NOT NULL, descricao VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', movimento_financeiro_id BIGINT UNSIGNED DEFAULT NULL, baixa_id BIGINT UNSIGNED DEFAULT NULL, importado_em DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX idx_extratos_bancarios_lookup (company_id, empresa_id, unidade_id, conta_financeira_id, data_movimento), CONSTRAINT FK_EXT_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_EXT_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_EXT_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_EXT_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE, CONSTRAINT FK_EXT_MOV FOREIGN KEY (movimento_financeiro_id) REFERENCES movimentos_financeiros (id) ON DELETE SET NULL, CONSTRAINT FK_EXT_BAIXA FOREIGN KEY (baixa_id) REFERENCES baixas (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE conciliacoes_bancarias (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, extrato_bancario_id BIGINT UNSIGNED NOT NULL, movimento_financeiro_id BIGINT UNSIGNED DEFAULT NULL, baixa_id BIGINT UNSIGNED DEFAULT NULL, modo VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'confirmada', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_CONC_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_CONC_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_CONC_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_CONC_EXT FOREIGN KEY (extrato_bancario_id) REFERENCES extratos_bancarios (id) ON DELETE CASCADE, CONSTRAINT FK_CONC_MOV FOREIGN KEY (movimento_financeiro_id) REFERENCES movimentos_financeiros (id) ON DELETE SET NULL, CONSTRAINT FK_CONC_BAIXA FOREIGN KEY (baixa_id) REFERENCES baixas (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE conciliacao_regras (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED DEFAULT NULL, unidade_id BIGINT UNSIGNED DEFAULT NULL, conta_financeira_id BIGINT UNSIGNED DEFAULT NULL, descricao_contains VARCHAR(255) NOT NULL, tipo_movimento_sugerido VARCHAR(20) NOT NULL, aplicacao VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', CONSTRAINT FK_REGRAS_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_REGRAS_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE SET NULL, CONSTRAINT FK_REGRAS_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE SET NULL, CONSTRAINT FK_REGRAS_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE integracoes_bancarias (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED DEFAULT NULL, unidade_id BIGINT UNSIGNED DEFAULT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, banco VARCHAR(100) NOT NULL, integration_type VARCHAR(50) NOT NULL, config_json JSON NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', CONSTRAINT FK_INTB_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_INTB_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE SET NULL, CONSTRAINT FK_INTB_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE SET NULL, CONSTRAINT FK_INTB_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("INSERT INTO modulos (codigo, nome, status) SELECT 'tesouraria', 'Tesouraria e Conciliação', 'active' WHERE NOT EXISTS (SELECT 1 FROM modulos WHERE codigo='tesouraria')");
        foreach ([['tesouraria.extratos.importar','Importar extratos bancários'],['tesouraria.extratos.view','Listar extratos bancários'],['tesouraria.conciliacoes.create','Criar conciliações'],['tesouraria.conciliacoes.view','Listar conciliações'],['tesouraria.conciliacao_regras.create','Criar regras de conciliação']] as [$codigo,$nome]) { $this->addSql("INSERT INTO permissoes (modulo_id, codigo, nome, status) SELECT id, '$codigo', '$nome', 'active' FROM modulos WHERE codigo='tesouraria' AND NOT EXISTS (SELECT 1 FROM permissoes WHERE codigo='$codigo')"); }
        $this->addSql("INSERT INTO perfil_acesso_permissoes (perfil_acesso_id, permissao_id) SELECT p.id, perm.id FROM perfis_acesso p JOIN permissoes perm ON perm.codigo LIKE 'tesouraria.%' WHERE p.codigo='company_admin' AND NOT EXISTS (SELECT 1 FROM perfil_acesso_permissoes x WHERE x.perfil_acesso_id=p.id AND x.permissao_id=perm.id)");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS integracoes_bancarias');
        $this->addSql('DROP TABLE IF EXISTS conciliacao_regras');
        $this->addSql('DROP TABLE IF EXISTS conciliacoes_bancarias');
        $this->addSql('DROP TABLE IF EXISTS extratos_bancarios');
    }
}
