<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260314250000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create BPO, workflow and automation tables with permissions.'; }
    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE tarefas_operacionais_bpo (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, titulo_id BIGINT UNSIGNED DEFAULT NULL, responsavel_user_id BIGINT UNSIGNED DEFAULT NULL, tipo VARCHAR(100) NOT NULL, descricao LONGTEXT NOT NULL, prioridade VARCHAR(20) NOT NULL DEFAULT 'media', status VARCHAR(30) NOT NULL DEFAULT 'aberta', prazo_em DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', KEY idx_tarefas_bpo_lookup (company_id, empresa_id, unidade_id, status, prioridade), CONSTRAINT FK_TBPO_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_TBPO_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_TBPO_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_TBPO_TITULO FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE SET NULL, CONSTRAINT FK_TBPO_RESP FOREIGN KEY (responsavel_user_id) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tarefas_operacionais_bpo_historico (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tarefa_operacional_bpo_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED DEFAULT NULL, acao VARCHAR(100) NOT NULL, observacao LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_TBPOH_TAREFA FOREIGN KEY (tarefa_operacional_bpo_id) REFERENCES tarefas_operacionais_bpo (id) ON DELETE CASCADE, CONSTRAINT FK_TBPOH_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE titulos_comentarios (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, titulo_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, comentario LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_TCOM_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_TCOM_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_TCOM_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_TCOM_TITULO FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE CASCADE, CONSTRAINT FK_TCOM_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aprovacoes_titulos (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, titulo_id BIGINT UNSIGNED NOT NULL, solicitante_user_id BIGINT UNSIGNED NOT NULL, tipo_operacao VARCHAR(100) NOT NULL, valor_total DECIMAL(18,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', KEY idx_aprovacoes_titulos_lookup (company_id, empresa_id, unidade_id, status), CONSTRAINT FK_APT_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_APT_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_APT_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_APT_TITULO FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE CASCADE, CONSTRAINT FK_APT_SOLICITANTE FOREIGN KEY (solicitante_user_id) REFERENCES users (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aprovacoes_titulos_itens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, aprovacao_titulo_id BIGINT UNSIGNED NOT NULL, aprovador_user_id BIGINT UNSIGNED NOT NULL, ordem INT NOT NULL, limite_alcada DECIMAL(18,2) DEFAULT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', observacao LONGTEXT DEFAULT NULL, decidido_em DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_APTI_APROVACAO FOREIGN KEY (aprovacao_titulo_id) REFERENCES aprovacoes_titulos (id) ON DELETE CASCADE, CONSTRAINT FK_APTI_APROVADOR FOREIGN KEY (aprovador_user_id) REFERENCES users (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE regras_automaticas_classificacao (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED DEFAULT NULL, unidade_id BIGINT UNSIGNED DEFAULT NULL, categoria_financeira_id BIGINT UNSIGNED DEFAULT NULL, centro_custo_id BIGINT UNSIGNED DEFAULT NULL, descricao_contains VARCHAR(255) NOT NULL, acao_notificacao TINYINT(1) NOT NULL DEFAULT 1, status VARCHAR(30) NOT NULL DEFAULT 'active', KEY idx_regras_auto_classificacao_lookup (company_id, empresa_id, unidade_id, status), CONSTRAINT FK_RAC_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_RAC_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE SET NULL, CONSTRAINT FK_RAC_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE SET NULL, CONSTRAINT FK_RAC_CATEGORIA FOREIGN KEY (categoria_financeira_id) REFERENCES categorias_financeiras (id) ON DELETE SET NULL, CONSTRAINT FK_RAC_CENTRO FOREIGN KEY (centro_custo_id) REFERENCES centros_custo (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE notificacoes_sistema (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED DEFAULT NULL, unidade_id BIGINT UNSIGNED DEFAULT NULL, user_id BIGINT UNSIGNED DEFAULT NULL, tipo VARCHAR(100) NOT NULL, titulo VARCHAR(255) NOT NULL, mensagem LONGTEXT NOT NULL, metadata_json JSON NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', KEY idx_notificacoes_sistema_lookup (company_id, empresa_id, unidade_id, status), CONSTRAINT FK_NS_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_NS_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE SET NULL, CONSTRAINT FK_NS_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE SET NULL, CONSTRAINT FK_NS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("INSERT INTO modulos (codigo, nome, status) SELECT 'bpo', 'BPO, Workflow e Automação', 'active' WHERE NOT EXISTS (SELECT 1 FROM modulos WHERE codigo='bpo')");
        foreach ([['bpo.tarefas.create','Criar tarefas BPO'],['bpo.tarefas.view','Listar tarefas BPO'],['bpo.titulos.comentarios.create','Comentar títulos'],['bpo.aprovacoes.create','Criar aprovações de títulos'],['bpo.regras_automaticas.create','Criar regras automáticas de classificação']] as [$codigo,$nome]) { $this->addSql("INSERT INTO permissoes (modulo_id, codigo, nome, status) SELECT id, '$codigo', '$nome', 'active' FROM modulos WHERE codigo='bpo' AND NOT EXISTS (SELECT 1 FROM permissoes WHERE codigo='$codigo')"); }
        $this->addSql("INSERT INTO perfil_acesso_permissoes (perfil_acesso_id, permissao_id) SELECT p.id, perm.id FROM perfis_acesso p JOIN permissoes perm ON perm.codigo LIKE 'bpo.%' WHERE p.codigo='company_admin' AND NOT EXISTS (SELECT 1 FROM perfil_acesso_permissoes x WHERE x.perfil_acesso_id=p.id AND x.permissao_id=perm.id)");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS notificacoes_sistema');
        $this->addSql('DROP TABLE IF EXISTS regras_automaticas_classificacao');
        $this->addSql('DROP TABLE IF EXISTS aprovacoes_titulos_itens');
        $this->addSql('DROP TABLE IF EXISTS aprovacoes_titulos');
        $this->addSql('DROP TABLE IF EXISTS titulos_comentarios');
        $this->addSql('DROP TABLE IF EXISTS tarefas_operacionais_bpo_historico');
        $this->addSql('DROP TABLE IF EXISTS tarefas_operacionais_bpo');
    }
}
