<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260314230000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create financeiro core tables and seed financeiro permissions.'; }
    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE titulos (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, pessoa_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED DEFAULT NULL, tipo VARCHAR(20) NOT NULL, numero_documento VARCHAR(100) DEFAULT NULL, valor_total DECIMAL(18,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'aberto', data_emissao DATE NOT NULL COMMENT '(DC2Type:date_immutable)', observacoes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX idx_titulos_lookup (company_id, empresa_id, unidade_id, tipo, status), CONSTRAINT FK_TIT_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_TIT_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_TIT_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_TIT_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoas (id) ON DELETE CASCADE, CONSTRAINT FK_TIT_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE titulos_parcelas (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, titulo_id BIGINT UNSIGNED NOT NULL, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, numero INT NOT NULL, valor DECIMAL(18,2) NOT NULL, valor_aberto DECIMAL(18,2) NOT NULL, vencimento DATE NOT NULL COMMENT '(DC2Type:date_immutable)', status VARCHAR(30) NOT NULL DEFAULT 'aberto', INDEX idx_titulos_parcelas_lookup (company_id, empresa_id, unidade_id, vencimento, status), CONSTRAINT FK_TITPAR_TIT FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE CASCADE, CONSTRAINT FK_TITPAR_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_TITPAR_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_TITPAR_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE baixas (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, titulo_parcela_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, valor DECIMAL(18,2) NOT NULL, data_pagamento DATE NOT NULL COMMENT '(DC2Type:date_immutable)', observacoes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_BAIXA_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_BAIXA_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_BAIXA_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_BAIXA_PARCELA FOREIGN KEY (titulo_parcela_id) REFERENCES titulos_parcelas (id) ON DELETE CASCADE, CONSTRAINT FK_BAIXA_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE movimentos_financeiros (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, empresa_id BIGINT UNSIGNED NOT NULL, unidade_id BIGINT UNSIGNED NOT NULL, conta_financeira_id BIGINT UNSIGNED NOT NULL, titulo_id BIGINT UNSIGNED DEFAULT NULL, baixa_id BIGINT UNSIGNED DEFAULT NULL, tipo VARCHAR(20) NOT NULL, valor DECIMAL(18,2) NOT NULL, data_movimento DATE NOT NULL COMMENT '(DC2Type:date_immutable)', historico LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_MOV_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_MOV_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE, CONSTRAINT FK_MOV_UNIDADE FOREIGN KEY (unidade_id) REFERENCES unidades_negocio (id) ON DELETE CASCADE, CONSTRAINT FK_MOV_CONTA FOREIGN KEY (conta_financeira_id) REFERENCES contas_financeiras (id) ON DELETE CASCADE, CONSTRAINT FK_MOV_TITULO FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE SET NULL, CONSTRAINT FK_MOV_BAIXA FOREIGN KEY (baixa_id) REFERENCES baixas (id) ON DELETE SET NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE anexos_financeiros (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, titulo_id BIGINT UNSIGNED NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, mime_type VARCHAR(100) DEFAULT NULL, uploaded_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', CONSTRAINT FK_ANEXO_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE, CONSTRAINT FK_ANEXO_TITULO FOREIGN KEY (titulo_id) REFERENCES titulos (id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("INSERT INTO modulos (codigo, nome, status) SELECT 'financeiro', 'Núcleo Financeiro', 'active' WHERE NOT EXISTS (SELECT 1 FROM modulos WHERE codigo='financeiro')");
        foreach ([['financeiro.titulos.create','Criar títulos'],['financeiro.titulos.view','Listar títulos'],['financeiro.titulos.parcelar','Parcelar títulos'],['financeiro.parcelas.baixar','Baixar parcelas']] as [$codigo,$nome]) { $this->addSql("INSERT INTO permissoes (modulo_id, codigo, nome, status) SELECT id, '$codigo', '$nome', 'active' FROM modulos WHERE codigo='financeiro' AND NOT EXISTS (SELECT 1 FROM permissoes WHERE codigo='$codigo')"); }
        $this->addSql("INSERT INTO perfil_acesso_permissoes (perfil_acesso_id, permissao_id) SELECT p.id, perm.id FROM perfis_acesso p JOIN permissoes perm ON perm.codigo LIKE 'financeiro.%' WHERE p.codigo='company_admin' AND NOT EXISTS (SELECT 1 FROM perfil_acesso_permissoes x WHERE x.perfil_acesso_id=p.id AND x.permissao_id=perm.id)");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS anexos_financeiros');
        $this->addSql('DROP TABLE IF EXISTS movimentos_financeiros');
        $this->addSql('DROP TABLE IF EXISTS baixas');
        $this->addSql('DROP TABLE IF EXISTS titulos_parcelas');
        $this->addSql('DROP TABLE IF EXISTS titulos');
    }
}
