<?php
declare(strict_types=1);
namespace App\Cadastro\Application\Service;
use App\Cadastro\Application\DTO\CreateContaFinanceiraRequest;
use App\Cadastro\Application\DTO\UpdateContaFinanceiraRequest;
use App\Cadastro\Domain\Entity\ContaFinanceira;
use App\Cadastro\Domain\Repository\BancoRepositoryInterface;
use App\Cadastro\Domain\Repository\ContaFinanceiraRepositoryInterface;
use App\Cadastro\Domain\Repository\PessoaRepositoryInterface;
use App\Company\Domain\Repository\CompanyRepositoryInterface;
use App\Company\Domain\Repository\EmpresaRepositoryInterface;
use App\Company\Domain\Repository\UnidadeNegocioRepositoryInterface;
use App\Shared\Application\Validation\RequestValidator;
use App\Shared\Domain\Contract\TransactionRunnerInterface;
use App\Shared\Domain\Exception\ResourceNotFoundException;
use App\Shared\Domain\Exception\ValidationException;
use App\Shared\Infrastructure\Auditoria\AuditoriaLogger;
final class ContaFinanceiraService {
    public function __construct(private readonly ContaFinanceiraRepositoryInterface $repo, private readonly BancoRepositoryInterface $bancoRepo, private readonly PessoaRepositoryInterface $pessoaRepo, private readonly CompanyRepositoryInterface $companyRepo, private readonly EmpresaRepositoryInterface $empresaRepo, private readonly UnidadeNegocioRepositoryInterface $unidadeRepo, private readonly RequestValidator $validator, private readonly TransactionRunnerInterface $tx, private readonly AuditoriaLogger $audit) {}
    public function create(CreateContaFinanceiraRequest $r): ContaFinanceira { $this->validator->validate($r); $company=$this->companyRepo->findById((int)$r->companyId); if(!$company){throw new ResourceNotFoundException('Company não encontrada.');} $empresa=$this->empresaRepo->findById((int)$r->empresaId); if($empresa===null||$empresa->getCompanyId()!==(int)$company->getId()){throw new ValidationException(['empresaId'=>['Empresa inválida para a company informada.']]);} $unidade=null; if($r->unidadeId!==null){$unidade=$this->unidadeRepo->findById($r->unidadeId); if($unidade===null||$unidade->getCompanyId()!==(int)$company->getId()){throw new ValidationException(['unidadeId'=>['Unidade inválida para a company informada.']]);}} $banco=null; if($r->bancoId!==null){$banco=$this->bancoRepo->findById($r->bancoId); if($banco===null){throw new ValidationException(['bancoId'=>['Banco inválido.']]);}} $titularPessoa=null; if($r->titularPessoaId!==null){$titularPessoa=$this->pessoaRepo->findById($r->titularPessoaId); if($titularPessoa===null||$titularPessoa->getCompanyId()!==(int)$company->getId()){throw new ValidationException(['titularPessoaId'=>['Titular inválido para a company informada.']]);}} $dataSaldoInicial=$r->dataSaldoInicial!==null?new \DateTimeImmutable($r->dataSaldoInicial):null; return $this->tx->run(function() use($r,$company,$empresa,$unidade,$banco,$titularPessoa,$dataSaldoInicial): ContaFinanceira { $c=new ContaFinanceira((int)$company->getId(),$empresa,$unidade,$banco,$titularPessoa,$r->codigo,$r->nome,$r->tipo,$r->agencia,$r->contaNumero,$r->contaDigito,$r->saldoInicial,$dataSaldoInicial,$r->permiteMovimentoNegativo,$r->status); $this->repo->save($c); $this->audit->log((int)$company->getId(),'conta_financeira','cadastro.conta_financeira.created',['contaFinanceiraId'=>$c->getId()]); return $c;}); }
    public function list(int $companyId, ?int $empresaId=null, ?string $status=null): array { return $this->repo->listAll($companyId,$empresaId,$status); }
    public function getById(int $id): ContaFinanceira { $conta=$this->repo->findById($id); if($conta===null){throw new ResourceNotFoundException('Conta financeira não encontrada.');} return $conta; }
    public function update(int $id, UpdateContaFinanceiraRequest $r): ContaFinanceira { $this->validator->validate($r); $conta=$this->getById($id); $company=$this->companyRepo->findById((int)$r->companyId); if(!$company||$conta->getCompanyId()!==$company->getId()){throw new ResourceNotFoundException('Company não encontrada.');} $empresa=$this->empresaRepo->findById((int)$r->empresaId); if($empresa===null||$empresa->getCompanyId()!==(int)$company->getId()){throw new ValidationException(['empresaId'=>['Empresa inválida para a company informada.']]);} $unidade=null; if($r->unidadeId!==null){$unidade=$this->unidadeRepo->findById($r->unidadeId); if($unidade===null||$unidade->getCompanyId()!==(int)$company->getId()){throw new ValidationException(['unidadeId'=>['Unidade inválida para a company informada.']]);}} $banco=null; if($r->bancoId!==null){$banco=$this->bancoRepo->findById($r->bancoId); if($banco===null){throw new ValidationException(['bancoId'=>['Banco inválido.']]);}} $titularPessoa=null; if($r->titularPessoaId!==null){$titularPessoa=$this->pessoaRepo->findById($r->titularPessoaId); if($titularPessoa===null||$titularPessoa->getCompanyId()!==(int)$company->getId()){throw new ValidationException(['titularPessoaId'=>['Titular inválido para a company informada.']]);}} $dataSaldoInicial=$r->dataSaldoInicial!==null?new \DateTimeImmutable($r->dataSaldoInicial):null; return $this->tx->run(function() use($conta,$r,$empresa,$unidade,$banco,$titularPessoa,$dataSaldoInicial): ContaFinanceira { $conta->update($empresa,$unidade,$banco,$titularPessoa,$r->codigo,$r->nome,$r->tipo,$r->agencia,$r->contaNumero,$r->contaDigito,$r->saldoInicial,$dataSaldoInicial,$r->permiteMovimentoNegativo,$r->status); $this->repo->save($conta); $this->audit->log((int)$conta->getCompanyId(),'conta_financeira','cadastro.conta_financeira.updated',['contaFinanceiraId'=>$conta->getId()]); return $conta;}); }
}
